spring:
  application:
    name: 2024-Partners-Backend
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true # 인코딩 설정 방식 강제성

logging:
  level:
    sql: debug
    org.hibernate.type : TRACE
    TechPartners.__Partners_Backend: DEBUG